# 자치구별 등급

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import os

In [2]:
os.chdir('C:/boram/데이터분석')

In [3]:
df = pd.read_csv('./alldata.csv')

In [4]:
df.head()

    지역  쓰레기발생량    주택수  1인가구 평균 배달일수   1인가구 비율
0  종로구   264.2  30259     12.687895  0.162980
1   중구   357.5  15263     13.326083  0.168956
2  용산구   301.2  36157     12.914051  0.150529
3  성동구   301.2  22673     12.816761  0.140947
4  광진구   343.1  56244     14.356042  0.172316

In [5]:
df2 = df.copy()

## 1. 쓰레기 발생량

In [6]:
# 구간 10개로 나누기
df['쓰레기발생량_그룹'] = pd.cut(df['쓰레기발생량'], bins = 10, labels = list(range(1,11,1)))
df

      지역  쓰레기발생량    주택수  1인가구 평균 배달일수   1인가구 비율 쓰레기발생량_그룹
0    종로구   264.2  30259     12.687895  0.162980         1
1     중구   357.5  15263     13.326083  0.168956         3
2    용산구   301.2  36157     12.914051  0.150529         2
3    성동구   301.2  22673     12.816761  0.140947         2
4    광진구   343.1  56244     14.356042  0.172316         3
5   동대문구   440.1  36905     13.424034  0.170052         5
6    중랑구   337.6  55329     12.412733  0.141335         2
7    성북구   361.6  57995     12.903445  0.136970         3
8    강북구   243.1  61677     12.495644  0.146065         1
9    도봉구   300.9  41398     11.527011  0.106123         2
10   노원구   394.8  25015     11.445173  0.106774         4
11   은평구   380.4  89977     12.061740  0.119177         3
12  서대문구   285.3  45971     12.666394  0.154069         1
13   마포구   366.4  50403     13.580340  0.164961         3
14   양천구   394.4  52122     11.166995  0.085847         4
15   강서구   526.8  80480     12.873248  0.146433         6
16   구로구   329.6  48714     12.408071  0.117118         2
17   금천구   274.5  36580     12.756069  0.169754         1
18  영등포구   449.4  31237     12.937981  0.157372         5
19   동작구   324.5  52914     12.838662  0.158855         2
20   관악구   401.6  70237     15.149475  0.252069         4
21   서초구   504.8  37768     12.127086  0.102306         6
22   강남구   694.9  45985     14.221517  0.126607        10
23   송파구   727.5  82768     12.702385  0.109152        10
24   강동구   368.0  49632     11.976966  0.108757         3

## 2. 주택수

In [7]:
# 구간 10개로 나누기
df2['주택수_그룹'] = pd.cut(df2['주택수'], bins = 10, labels = list(range(1,11,1)))
df2

      지역  쓰레기발생량    주택수  1인가구 평균 배달일수   1인가구 비율 쓰레기발생량_그룹 주택수_그룹
0    종로구   264.2  30259     12.687895  0.162980         1      3
1     중구   357.5  15263     13.326083  0.168956         3      1
2    용산구   301.2  36157     12.914051  0.150529         2      3
3    성동구   301.2  22673     12.816761  0.140947         2      1
4    광진구   343.1  56244     14.356042  0.172316         3      6
5   동대문구   440.1  36905     13.424034  0.170052         5      3
6    중랑구   337.6  55329     12.412733  0.141335         2      6
7    성북구   361.6  57995     12.903445  0.136970         3      6
8    강북구   243.1  61677     12.495644  0.146065         1      7
9    도봉구   300.9  41398     11.527011  0.106123         2      4
10   노원구   394.8  25015     11.445173  0.106774         4      2
11   은평구   380.4  89977     12.061740  0.119177         3     10
12  서대문구   285.3  45971     12.666394  0.154069         1      5
13   마포구   366.4  50403     13.580340  0.164961         3      5
14   양천구   394.4  52122     11.166995  0.085847         4      5
15   강서구   526.8  80480     12.873248  0.146433         6      9
16   구로구   329.6  48714     12.408071  0.117118         2      5
17   금천구   274.5  36580     12.756069  0.169754         1      3
18  영등포구   449.4  31237     12.937981  0.157372         5      3
19   동작구   324.5  52914     12.838662  0.158855         2      6
20   관악구   401.6  70237     15.149475  0.252069         4      8
21   서초구   504.8  37768     12.127086  0.102306         6      4
22   강남구   694.9  45985     14.221517  0.126607        10      5
23   송파구   727.5  82768     12.702385  0.109152        10     10
24   강동구   368.0  49632     11.976966  0.108757         3      5

## 3. 1인가구 평균 배달일수

In [8]:
# 구간 10개로 나누기
df2['1인가구 평균 배달일수_그룹'] = pd.cut(df2['1인가구 평균 배달일수'], bins = 10, labels = list(range(1,11,1)))
df2

,지역,쓰레기발생량,주택수,1인가구 평균 배달일수,1인가구 비율,쓰레기발생량_그룹,주택수_그룹,1인가구 평균 배달일수_그룹
0,종로구,264.2,30259,12.687895,0.162980,1,3,4
1,중구,357.5,15263,13.326083,0.168956,3,1,6
2,용산구,301.2,36157,12.914051,0.150529,2,3,5
3,성동구,301.2,22673,12.816761,0.140947,2,1,5
4,광진구,343.1,56244,14.356042,0.172316,3,6,9
5,동대문구,440.1,36905,13.424034,0.170052,5,3,6
6,중랑구,337.6,55329,12.412733,0.141335,2,6,4
7,성북구,361.6,57995,12.903445,0.136970,3,6,5
8,강북구,243.1,61677,12.495644,0.146065,1,7,4
9,도봉구,300.9,41398,11.527011,0.106123,2,4,1
10,노원구,394.8,25015,11.445173,0.106774,4,2,1
11,은평구,380.4,89977,12.061740,0.119177,3,10,3
12,서대문구,285.3,45971,12.666394,0.154069,1,5,4
13,마포구,366.4,50403,13.580340,0.164961,3,5,7
14,양천구,394.4,52122,11.166995,0.085847,4,5,1
15,강서구,526.8,80480,12.873248,0.146433,6,9,5
16,구로구,329.6,48714,12.408071,0.117118,2,5,4
17,금천구,274.5,36580,12.756069,0.169754,1,3,4
18,영등포구,449.4,31237,12.937981,0.157372,5,3,5
19,동작구,324.5,52914,12.838662,0.158855,2,6,5
20,관악구,401.6,70237,15.149475,0.252069,4,8,10
21,서초구,504.8,37768,12.127086,0.102306,6,4,3
22,강남구,694.9,45985,14.221517,0.126607,10,5,8
23,송파구,727.5,82768,12.702385,0.109152,10,10,4
24,강동구,368.0,49632,11.976966,0.108757,3,5,3

## 4. 1인가구 비율

In [9]:
# 구간 10개로 나누기
df2['1인가구 비율_그룹'] = pd.cut(df2['1인가구 비율'], bins = 10, labels = list(range(1,11,1)))
df2

,지역,쓰레기발생량,주택수,1인가구 평균 배달일수,1인가구 비율,쓰레기발생량_그룹,주택수_그룹,1인가구 평균 배달일수_그룹,1인가구 비율_그룹
0,종로구,264.2,30259,12.687895,0.162980,1,3,4,5
1,중구,357.5,15263,13.326083,0.168956,3,1,6,5
2,용산구,301.2,36157,12.914051,0.150529,2,3,5,4
3,성동구,301.2,22673,12.816761,0.140947,2,1,5,4
4,광진구,343.1,56244,14.356042,0.172316,3,6,9,6
5,동대문구,440.1,36905,13.424034,0.170052,5,3,6,6
6,중랑구,337.6,55329,12.412733,0.141335,2,6,4,4
7,성북구,361.6,57995,12.903445,0.136970,3,6,5,4
8,강북구,243.1,61677,12.495644,0.146065,1,7,4,4
9,도봉구,300.9,41398,11.527011,0.106123,2,4,1,2
10,노원구,394.8,25015,11.445173,0.106774,4,2,1,2
11,은평구,380.4,89977,12.061740,0.119177,3,10,3,3
12,서대문구,285.3,45971,12.666394,0.154069,1,5,4,5
13,마포구,366.4,50403,13.580340,0.164961,3,5,7,5
14,양천구,394.4,52122,11.166995,0.085847,4,5,1,1
15,강서구,526.8,80480,12.873248,0.146433,6,9,5,4
16,구로구,329.6,48714,12.408071,0.117118,2,5,4,2
17,금천구,274.5,36580,12.756069,0.169754,1,3,4,6
18,영등포구,449.4,31237,12.937981,0.157372,5,3,5,5
19,동작구,324.5,52914,12.838662,0.158855,2,6,5,5
20,관악구,401.6,70237,15.149475,0.252069,4,8,10,10
21,서초구,504.8,37768,12.127086,0.102306,6,4,3,1
22,강남구,694.9,45985,14.221517,0.126607,10,5,8,3
23,송파구,727.5,82768,12.702385,0.109152,10,10,4,2
24,강동구,368.0,49632,11.976966,0.108757,3,5,3,2

## 합계

In [10]:
df2['쓰레기발생량_그룹'] = df2['쓰레기발생량_그룹'].astype('int')
df2['주택수_그룹'] = df2['주택수_그룹'].astype('int')
df2['1인가구 평균 배달일수_그룹'] = df2['1인가구 평균 배달일수_그룹'].astype('int')
df2['1인가구 비율_그룹'] = df2['1인가구 비율_그룹'].astype('int')

df2['sum'] = df2['쓰레기발생량_그룹'] + df2['주택수_그룹'] + df2['1인가구 평균 배달일수_그룹'] + df2['1인가구 비율_그룹']
df2

,지역,쓰레기발생량,주택수,1인가구 평균 배달일수,1인가구 비율,쓰레기발생량_그룹,주택수_그룹,1인가구 평균 배달일수_그룹,1인가구 비율_그룹,sum
0,종로구,264.2,30259,12.687895,0.162980,1,3,4,5,13
1,중구,357.5,15263,13.326083,0.168956,3,1,6,5,15
2,용산구,301.2,36157,12.914051,0.150529,2,3,5,4,14
3,성동구,301.2,22673,12.816761,0.140947,2,1,5,4,12
4,광진구,343.1,56244,14.356042,0.172316,3,6,9,6,24
5,동대문구,440.1,36905,13.424034,0.170052,5,3,6,6,20
6,중랑구,337.6,55329,12.412733,0.141335,2,6,4,4,16
7,성북구,361.6,57995,12.903445,0.136970,3,6,5,4,18
8,강북구,243.1,61677,12.495644,0.146065,1,7,4,4,16
9,도봉구,300.9,41398,11.527011,0.106123,2,4,1,2,9
10,노원구,394.8,25015,11.445173,0.106774,4,2,1,2,9
11,은평구,380.4,89977,12.061740,0.119177,3,10,3,3,19
12,서대문구,285.3,45971,12.666394,0.154069,1,5,4,5,15
13,마포구,366.4,50403,13.580340,0.164961,3,5,7,5,20
14,양천구,394.4,52122,11.166995,0.085847,4,5,1,1,11
15,강서구,526.8,80480,12.873248,0.146433,6,9,5,4,24
16,구로구,329.6,48714,12.408071,0.117118,2,5,4,2,13
17,금천구,274.5,36580,12.756069,0.169754,1,3,4,6,14
18,영등포구,449.4,31237,12.937981,0.157372,5,3,5,5,18
19,동작구,324.5,52914,12.838662,0.158855,2,6,5,5,18
20,관악구,401.6,70237,15.149475,0.252069,4,8,10,10,32
21,서초구,504.8,37768,12.127086,0.102306,6,4,3,1,14
22,강남구,694.9,45985,14.221517,0.126607,10,5,8,3,26
23,송파구,727.5,82768,12.702385,0.109152,10,10,4,2,26
24,강동구,368.0,49632,11.976966,0.108757,3,5,3,2,13

In [13]:
df3 = df2.sort_values('sum', ascending = False)[['지역', 'sum']]
df3

      지역  sum
20   관악구   32
22   강남구   26
23   송파구   26
4    광진구   24
15   강서구   24
13   마포구   20
5   동대문구   20
11   은평구   19
19   동작구   18
7    성북구   18
18  영등포구   18
6    중랑구   16
8    강북구   16
12  서대문구   15
1     중구   15
21   서초구   14
2    용산구   14
17   금천구   14
0    종로구   13
16   구로구   13
24   강동구   13
3    성동구   12
14   양천구   11
10   노원구    9
9    도봉구    9

In [14]:
df3.to_csv('자치구별 등급.csv', index = False, encoding='utf-8-sig')